### ISSUE TITLE
DB ERROR during the creating of new appointments

### ISSUE THREAD

**Issue by s1mp73x** [daniel-lerch/openkool#2]
When I try to create a new appointment, I will get the following DB ERROR:
DB ERROR (db_insert_data): 1364: Field 'comments' doesn't have a default value, QUERY: INSERT INTO `ko_reservation` (`item_id`, `startdatum`, `enddatum`, `zweck`, `name`, `email`, `telefon`, `user_id`, `startzeit`, `endzeit`, `code`, `last_change`, `linked_items`, `cdate`) VALUES ('4', '2019-09-10', '2019-09-10', 'Abendveranstaltung (Abendveranstaltung)', 'xxx', 'xxx', 'xxx', '12', '19:00', '22:00', 'b364623d', '2019-09-09 20:53:07', '', '2019-09-09 20:53:07')

**Comment by Twometer** [comment]
From this one screenshot, I can get an email, a phone number, an IP address and a full real name. Maybe this should not be public?

**Comment by s1mp73x** [comment]
Screenshot removed and relevant data obfuscated, thanks for that hint :-)

**Comment by Twometer** [comment]
@s1mp73x I can still see the old revision, maybe delete that also :D
