### ISSUE TITLE
Can not connect to database!

### ISSUE THREAD

**Issue by zimmerlis** [daniel-lerch/openkool#22]
I followed the instruction on : https://github.com/daniel-lerch/openkool/blob/master/docs/install.md
I did the installation on docker of Synology NAS, and what I am missing is the HOSTNAME of Maria DB that is already running on Synology itself.:

    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=kool
      - MYSQL_USER=kool
      - MYSQL_PASSWORD=
      **- MYSQL_HOST=172.17.0.1** ??

I think that I don't need such a volume, if MARIA DB is already running on Synology.
    volumes:
      - db:/var/lib/mysql

**Comment by daniel-lerch** [comment]
May I help you via call? That would save both of us a lot of time. If so, please send me an email to daniel.dev@lerchen.net so that I can send you a link.

**Comment by daniel-lerch** [comment]
OpenKool does not use environment variables for its database configuration. You have to run the web installer and enter your database settings in the browser.
